### Tasks

* 1. Create a Python script that loads a sample image (use any image of your favorite cricketer or celebrity), converts it to a NumPy array, and prints the array shape to demonstrate how images are represented for CNNs.

In [1]:
import numpy as np
from PIL import Image

In [2]:
image_path = r"C:\Users\patel prit\OneDrive\Desktop\Assessment\DL\Assignment\Session - 18\Harry Potter.webp"

In [3]:
try:
    img = Image.open(image_path)
    img_array = np.array(img)
    print("Image Representation for CNNs:")
    print(f"Numpy Array Shape: {img_array.shape}")
    print(f"Data Type:         {img_array.dtype}")

    if img_array.ndim == 3:
        h, w, c = img_array.shape
        print(f"\nBreakdown: Height = {h}px, Width = {w}px, Channels = {c} (RGB)")
    else:
        h, w = img_array.shape
        print(f"\nBreakdown: Height = {h}px, Width = {w}px (Grayscale)")

except FileNotFoundError:
    print(f"File '{image_path}' not found. Please Provide a valid image path.")

Image Representation for CNNs:
Numpy Array Shape: (978, 652, 3)
Data Type:         uint8

Breakdown: Height = 978px, Width = 652px, Channels = 3 (RGB)


* 2. Implement a simple 2D convolution operation in Python using NumPy: given a 5x5 grayscale image array and a 3x3 filter, compute the output feature map without using any deep learning libraries.<br><br><em><strong>Hint:</strong> Use nested loops to slide the filter over the image and sum the element-wise products.</em>

In [4]:
image = np.array([
    [1, 2, 3, 0, 1],
    [0, 1, 2, 4, 1],
    [3, 1, 0, 2, 0],
    [1, 0, 1, 3, 2],
    [2, 1, 0, 1, 1]
])

In [5]:
filter_kernel = np.array([
    [ 1,  0, -1],
    [ 1,  0, -1],
    [ 1,  0, -1]
])

In [6]:
img_h, img_w = image.shape
f_h, f_w = filter_kernel.shape

In [7]:
out_h = img_h - f_h + 1
out_w = img_w - f_w + 1

In [8]:
output_feature_map = np.zeros((out_h, out_w))

In [9]:
for i in range(out_h):
    for j in range(out_w):
        region = image[i:i+f_h, j:j+f_w]

        output_feature_map[i, j] = np.sum(region * filter_kernel)

In [10]:
print("* 5x5 Input Image:")
print(image)
print("\n* 3x3 Kernel:")
print(filter_kernel)
print("\n* Output Feature Map (3x3):")
print(output_feature_map)

* 5x5 Input Image:
[[1 2 3 0 1]
 [0 1 2 4 1]
 [3 1 0 2 0]
 [1 0 1 3 2]
 [2 1 0 1 1]]

* 3x3 Kernel:
[[ 1  0 -1]
 [ 1  0 -1]
 [ 1  0 -1]]

* Output Feature Map (3x3):
[[-1. -2.  3.]
 [ 1. -7.  0.]
 [ 5. -4. -2.]]


* 3. Draw the architecture diagram of a basic CNN (on paper or using a tool like draw.io) showing input layer, one convolutional layer, one pooling layer, and an output layer. Label each part and briefly describe its function in 1-2 lines.

```mermaid
graph LR
    subgraph Input ["Input Layer"]
        A["28 x 28 x 3"]
    end

    subgraph Conv ["Convolutional Layer"]
        B["Filters / Feature Maps"]
    end

    subgraph Pool ["Pooling Layer"]
        C["Max Pooling"]
    end

    subgraph Output ["Output Layer"]
        D["Dense / Softmax"]
    end

    A --> B --> C --> D

**Component Descriptions** 
* Input Layer: Receives the raw numerical pixel values of the image (e.g., $28 \times 28 \times 3$ array for RGB) and passes them into the network.

* Convolutional Layer: Applies sliding filters across the input to perform element-wise multiplication, extracting spatial features like edges, textures, and lines into feature maps.
* Pooling Layer: Downsamples feature maps (e.g., using $2 \times 2$ max pooling) to reduce spatial dimensions, lower computational costs, and prevent overfitting.
* Output Layer: Flattens spatial feature vectors and applies fully connected neurons with an activation function (like Softmax) to compute final class probability scores.

* 4. Write a function in Python that takes an image array and returns a new array where each pixel is replaced by the maximum value in its 2x2 local neighborhood (simulate max pooling).<br><br><em><strong>Constraint:</strong> Do not use any deep learning libraries like TensorFlow or PyTorch for this task.</em>

In [11]:
def max_pooling_2d(image_array, pool_size=(2, 2), stride=2):
    img_h, img_w = image_array.shape
    p_h, p_w = pool_size
    
    out_h = (img_h - p_h) // stride + 1
    out_w = (img_w - p_w) // stride + 1
    
    pooled_output = np.zeros((out_h, out_w), dtype=image_array.dtype)
    
    for i in range(out_h):
        for j in range(out_w):
            row_start = i * stride
            col_start = j * stride
            
            region = image_array[row_start:row_start+p_h, col_start:col_start+p_w]
            
            pooled_output[i, j] = np.max(region)
            
    return pooled_output

In [12]:
sample_image = np.array([
    [1, 3, 2, 4],
    [5, 6, 1, 2],
    [8, 7, 0, 1],
    [2, 4, 3, 5]
])

In [13]:
result = max_pooling_2d(sample_image)

In [14]:
print("* Original 4x4 Array:")
print(sample_image)
print("\n* Max Pooled 2x2 Array:")
print(result)

* Original 4x4 Array:
[[1 3 2 4]
 [5 6 1 2]
 [8 7 0 1]
 [2 4 3 5]]

* Max Pooled 2x2 Array:
[[6 4]
 [8 5]]


* 5. Explain with a real-world example from Instagram or Zomato how translation invariance in CNNs is useful. Write 2-3 sentences connecting it to how these apps recognize faces or food items even if they appear in different positions in the image.

**Real-World Example — Translation Invariance**

When users upload food photos to Zomato or selfies to Instagram, a pizza or face might appear centered, off-to-the-side, or in a corner of the image frame.

**Translation invariance** ensures that because CNNs use sliding shared-weight filters and spatial reduction (pooling layers), they identify key localized patterns—such as the circular crust of a pizza or facial features—regardless of where those features are located in the pixel matrix. Consequently, these applications can correctly identify and auto-tag objects or faces even if their position shifts across different images.