### Tasks

* 1. Create a 6x6 NumPy array with random integers (0-255) to simulate a grayscale image, then apply a 2x2 max pooling operation with a stride of 2 and print the resulting reduced array.

In [47]:
import numpy as np

In [48]:
np.random.seed(42)

In [49]:
image_1 = np.random.randint(0, 255,size=(6, 6))

In [50]:
pool_size = 2
stride = 2

In [51]:
out_h = image_1.shape[0] // stride
out_w = image_1.shape[1] // stride

In [52]:
max_pooled_1 = np.zeros((out_h, out_w), dtype=int)

In [53]:
for i in range(out_h):
    for j in range(out_w):
        r = i * stride
        c = j * stride
        region = image_1[r:r+pool_size, c:c+pool_size]
        max_pooled_1[i, j] = np.max(region)

In [54]:
print("* Simulated 6X6 GrayScale Image:")
print(image_1)
print("\n* Reduced 3X3 Max Pooled Output:")
print(max_pooled_1)

* Simulated 6X6 GrayScale Image:
[[102 179  92  14 106  71]
 [188  20 102 121 210 214]
 [ 74 202  87 116  99 103]
 [151 130 149  52   1  87]
 [235 157  37 129 191 187]
 [ 20 160 203  57  21 252]]

* Reduced 3X3 Max Pooled Output:
[[188 121 214]
 [202 149 103]
 [235 203 252]]


* 2. Write a Python function average_pooling_2x2(image) that takes a 2D NumPy array and returns a new array after applying 2x2 average pooling with stride 2.

In [55]:
def average_pooling_2x2(image):
    pool_size = 2
    stride = 2

    in_h, in_w = image.shape
    out_h = in_h // stride
    out_w = in_w // stride

    pooled_array = np.zeros((out_h, out_w), dtype=np.float32)

    for i in range(out_h):
        for j in range(out_w):
            r = i * stride
            c = j * stride
            
            region = image[r:r+pool_size, c:c+pool_size]
            pooled_array[i, j] = np.mean(region)

    return pooled_array

In [56]:
sample_matrix = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [12, 24, 36, 48],
    [60, 72, 84, 96]
])

In [57]:
print("* Original Array:")
print(sample_matrix)
print("\n* 2X2 Average Pooled Array:")
print(average_pooling_2x2(sample_matrix))

* Original Array:
[[10 20 30 40]
 [50 60 70 80]
 [12 24 36 48]
 [60 72 84 96]]

* 2X2 Average Pooled Array:
[[35. 55.]
 [42. 66.]]


* 3. Given a 4x4 feature map array, manually perform both max pooling and average pooling with a 2x2 window and stride 2, and compare the results side by side.<br><br><em><strong>Hint:</strong> Show both resulting arrays and explain in one line which pooling method keeps more details from the original image.</em>

In [58]:
feature_map = np.array([
    [12, 20,  0,  8],
    [ 4, 32,  2, 14],
    [10, 10, 80, 20],
    [ 2,  6, 40, 10]
])

In [59]:
max_pool = np.zeros((2, 2))
avg_pool = np.zeros((2, 2))

In [60]:
for i in range(2):
    for j in range(2):
        region = feature_map[i*2:i*2+2, j*2:j*2+2]
        max_pool[i, j] = np.max(region)
        avg_pool[i, j] = np.mean(region)

In [61]:
print("* 4X4 Feature Map:")
print(feature_map)
print("\n* Side-by-Side Comparison")
print("Max Pooled (2X2):")
print(max_pool)
print("\nAverage Pooled (2X2):")
print(avg_pool)

* 4X4 Feature Map:
[[12 20  0  8]
 [ 4 32  2 14]
 [10 10 80 20]
 [ 2  6 40 10]]

* Side-by-Side Comparison
Max Pooled (2X2):
[[32. 14.]
 [10. 80.]]

Average Pooled (2X2):
[[17.   6. ]
 [ 7.  37.5]]


**Key Difference:**

Average Pooling keeps more overall details and structural background context from the original image by smoothing pixel values, whereas Max Pooling aggressively discards low values to preserve only the most prominent, dominant features (like strong edges).

* 4. Combine a single 3x3 convolution layer (use any simple filter, e.g., edge detection) followed by a 2x2 max pooling layer on a 5x5 input array. Show the output after each step.

In [62]:
input_4 = np.array([
    [1, 2, 3, 0, 1],
    [0, 1, 2, 4, 1],
    [3, 1, 0, 2, 0],
    [1, 0, 1, 3, 2],
    [2, 1, 0, 1, 1]
])

edge_filter = np.array([
    [ 1,  0, -1],
    [ 1,  0, -1],
    [ 1,  0, -1]
])

In [63]:
conv_out = np.zeros((3, 3))
for i in range(3):
    for j in range(3):
        region = input_4[i:i+3, j:j+3]
        conv_out[i, j] = np.sum(region * edge_filter)

In [64]:
pool_out = np.zeros((2, 2))
for i in range(2):
    for j in range(2):
        region = conv_out[i:i+2, j:j+2]
        pool_out[i, j] = np.max(region)

In [65]:
print("1. Original 5x5 Input:")
print(input_4)
print("\n2. After 3x3 Convolution (3x3 Feature Map):")
print(conv_out)
print("\n3. After 2x2 Max Pooling (2x2 Feature Map):")
print(pool_out)

1. Original 5x5 Input:
[[1 2 3 0 1]
 [0 1 2 4 1]
 [3 1 0 2 0]
 [1 0 1 3 2]
 [2 1 0 1 1]]

2. After 3x3 Convolution (3x3 Feature Map):
[[-1. -2.  3.]
 [ 1. -7.  0.]
 [ 5. -4. -2.]]

3. After 2x2 Max Pooling (2x2 Feature Map):
[[1. 3.]
 [5. 0.]]


* 5. Explain in your own words, using an example from Instagram or Zomato, how pooling layers help reduce computation and improve feature extraction in deep learning models.

**Real-World Concept — Pooling in Instagram/Zomato**

**1. Reducing Computation**

When you upload a high-resolution food photo to Zomato or a selfie to Instagram, the image can contain millions of pixel inputs. A pooling layer downsizes the image representations (e.g., halving the height and width cuts total pixel memory by 75%), drastically reducing the matrix parameters that downstream neural network layers need to process. This enables fast real-time image processing on mobile devices.

**2. Improving Feature Extraction**

If a CNN detects a food dish (e.g., a burger) on Zomato, Max Pooling extracts only the highest activation values from local pixel regions. It focuses on sharp, defining characteristics—such as the curve of the burger bun or the texture of sesame seeds—while ignoring minor background noise or lighting shifts. This ensures that even if the dish moves slightly or has minor background variations, the model reliably identifies the key item.