### Tasks

* 1. Install the transformers and torch libraries using pip, then write a Python script that prints the version numbers of both libraries to confirm successful installation.

In [11]:
!pip install transformers torch -q


[notice] A new release of pip is available: 26.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [12]:
import transformers
import torch

In [13]:
transformers.__version__

'5.17.0'

In [14]:
torch.__version__

'2.13.0+cpu'

* 2. Write a short paragraph (2-3 sentences) explaining one limitation of traditional NLP models (like Bag of Words or TF-IDF) when trying to understand the meaning of a WhatsApp chat message.

* 3. Use the Hugging Face pipeline to perform sentiment analysis on three recent Zomato or Swiggy app reviews (copy-paste the review text) and print the predicted sentiment for each.

In [15]:
from transformers import pipeline

In [ ]:
sentiment_pipeline = pipeline('sentiment-analysis')

In [ ]:
reviews = [
    'The delivery was incredibly fast and the food was hot!',
    'Worst biryani I have ever had, completely tasteless.',
    'Decent portion size but a bit overpriced for what you get.'
]

In [ ]:
for review in reviews:
    result = sentiment_pipeline(review)[0]
    print(f"Review: '{review}'\nPredicted Sentiment: {result['label']} (Score: {result['score']})\n")

* 4. Find out the name of a popular transformer model used for text classification (other than BERT) using the Hugging Face model hub, and write 2 lines about what makes it different from BERT.<br><br><em><strong>Hint:</strong> Visit https://huggingface.co/models and search for text classification models.</em>

* 5. Use ChatGPT or Copilot to generate a simple Python function that demonstrates the attention mechanism with three short sentences as input, and explain in your own words (2-3 lines) what the attention scores mean in your output.<br><br><em><strong>Hint:</strong> Ask the AI tool to 'show a basic attention calculation example in Python.'</em>

In [16]:
import numpy as np

def simple_attention(query, keys, values):
    scores = np.dot(query, keys.T)
    weights = np.exp(scores) / np.sum(np.exp(scores), axis=-1, keepdims=True)
    output = np.dot(weights, values)
    return output, weights

In [17]:
sentences = ['I love food', 'Food is good', 'I am hungry']
# Dummy embeddings for the 3 sentences (size=4)
embeddings = np.array([
    [0.1, 0.2, 0.3, 0.4],
    [0.2, 0.3, 0.4, 0.5],
    [0.9, 0.8, 0.7, 0.6]
])

In [18]:
query = embeddings 
keys = embeddings
values = embeddings

output, attention_weights = simple_attention(query, keys, values)

print('Attention Weights Matrix:\n', np.round(attention_weights, 4))

Attention Weights Matrix:
 [[0.278  0.3072 0.4147]
 [0.2517 0.2896 0.4587]
 [0.1369 0.1848 0.6782]]
