### Tasks

* 1. Create a 5x5 NumPy matrix with random integers from 0 to 9, then define a 3x3 filter (kernel) and manually perform a single convolution operation (no padding, stride 1) to produce the activation map.

In [56]:
import numpy as np

In [57]:
np.random.seed(42)

In [58]:
input_1 = np.random.randint(0, 10, size=(5, 5))

kernal_1 = np.array([
    [1, 0, -1],
    [1, 0, -1],
    [1, 0, -1]
])

In [59]:
in_h, in_w = input_1.shape
k_h, k_w = kernal_1.shape

In [60]:
out_h = in_h - k_h + 1
out_w = in_w - k_w + 1

In [61]:
activation_map = np.zeros((out_h, out_w))

In [62]:
for i in range(out_h):
    for j in range(out_w):
        region = input_1[i:i+k_h, j:j+k_w]
        activation_map[i, j] = np.sum(region * kernal_1)

In [63]:
print("* 5x5 Input Matrix:")
print(input_1)
print("\n* 3x3 Kernel:")
print(kernal_1)
print("\n* Resulting 3x3 Activation Map:")
print(activation_map)

* 5x5 Input Matrix:
[[6 3 7 4 6]
 [9 2 6 7 4]
 [3 7 7 2 5]
 [4 1 7 5 1]
 [4 0 9 5 8]]

* 3x3 Kernel:
[[ 1  0 -1]
 [ 1  0 -1]
 [ 1  0 -1]]

* Resulting 3x3 Activation Map:
[[ -2.  -1.   5.]
 [ -4.  -4.  10.]
 [-12.  -4.   9.]]


* 2. Implement a Python function apply_stride_convolution(input_matrix, kernel, stride) that performs convolution with a given stride on a 6x6 matrix and a 3x3 kernel, returning the resulting activation map.<br><br><em><strong>Hint:</strong> Use nested loops to move the kernel by the stride value over the input matrix.</em>

In [64]:
def apply_stride_convolution(input_matrix, kernel, stride=1):
    in_h, in_w = input_matrix.shape
    k_h, k_w = kernel.shape
    
    out_h = (in_h - k_h) // stride + 1
    out_w = (in_w - k_w) // stride + 1
    
    activation_map = np.zeros((out_h, out_w))
    
    for i in range(out_h):
        for j in range(out_w):
            r_start = i * stride
            c_start = j * stride
            
            region = input_matrix[r_start:r_start+k_h, c_start:c_start+k_w]
            activation_map[i, j] = np.sum(region * kernel)
            
    return activation_map

In [65]:
np.random.seed(10)
input_2 = np.random.randint(0, 10, size=(6, 6))
kernel_2 = np.array([
    [1, 1, 1],
    [0, 0, 0],
    [-1, -1, -1]
])

In [66]:
output_stride_2 = apply_stride_convolution(input_2, kernel_2, stride=2)

In [67]:
print("* 6x6 Input Matrix:")
print(input_2)
print("\n* Activation Map (Stride = 2):")
print(output_stride_2)

* 6x6 Input Matrix:
[[9 4 0 1 9 0]
 [1 8 9 0 8 6]
 [4 3 0 4 6 8]
 [1 8 4 1 3 6]
 [5 3 9 6 9 1]
 [9 4 2 6 7 8]]

* Activation Map (Stride = 2):
[[  6.   0.]
 [-10. -14.]]


* 3. Modify your convolution code to add zero-padding of 1 around the input matrix before applying the convolution, and show the new activation map output.

Adding $P = 1$ zero-padding expands a $5 \times 5$ matrix to $7 \times 7$. Applying a $3 \times 3$ kernel with stride 1 returns an output equal in size to the original input ($5 \times 5$).

In [68]:
def apply_padded_convolution(input_matrix, kernel, padding=1, stride=1):
    padded_input = np.pad(input_matrix, pad_width=padding, mode='constant', constant_values=0)
    return apply_stride_convolution(padded_input, kernel, stride=stride), padded_input

In [69]:
input_3 = np.array([
    [6, 3, 7, 4, 6],
    [9, 2, 6, 7, 4],
    [3, 7, 7, 2, 5],
    [4, 1, 7, 5, 1],
    [4, 0, 9, 5, 8]
])

In [70]:
kernel_3 = np.array([
    [0, 1, 0],
    [1, -4, 1],
    [0, 1, 0]
])

In [71]:
padded_map, padded_matrix = apply_padded_convolution(input_3, kernel_3, padding=1, stride=1)

In [73]:
print("* Padded Input Matrix (7x7):")
print(padded_matrix)
print("\n* New Activation Map Output (5x5):")
print(padded_map)

* Padded Input Matrix (7x7):
[[0 0 0 0 0 0 0]
 [0 6 3 7 4 6 0]
 [0 9 2 6 7 4 0]
 [0 3 7 7 2 5 0]
 [0 4 1 7 5 1 0]
 [0 4 0 9 5 8 0]
 [0 0 0 0 0 0 0]]

* New Activation Map Output (5x5):
[[-12.   3. -15.   4. -16.]
 [-25.  17.  -1. -12.   2.]
 [  8. -15.  -6.  16. -13.]
 [ -8.  14.  -6.  -5.  14.]
 [-12.  14. -24.   2. -26.]]


* 4. Visualize the effect of different filters by applying both an edge detection kernel and a blur kernel to the same 5x5 matrix and print both activation maps side by side.<br><br><em><strong>Hint:</strong> Use the Sobel or Laplacian kernel for edge detection and an averaging kernel for blur.</em>

In [82]:
np.random.seed(1)
matrix_4 = np.random.randint(10, 50, size=(5, 5))

edge_kernel_4 = np.array([
    [ 0, -1,  0],
    [-1,  4, -1],
    [ 0, -1,  0]
])

blur_kernel = np.ones((3, 3)) / 9.0

In [83]:
edge_map = apply_stride_convolution(matrix_4, edge_kernel_4, stride=1)
blur_map = apply_stride_convolution(matrix_4, blur_kernel, stride=1)

In [90]:
print("* 5x5 Input Matrix:")
print(matrix_4)
print("\n" + "="*50)
print(f"{'Edge Detection Map':<25} | {'Blur Activation Map':<25}")
print("="*50)

for row1, row2 in zip(edge_map, blur_map):
    str_r1 = str([f"{val:4.1f}" for val in row1])
    str_r2 = str([f"{val:4.1f}" for val in row2])
    print(f"{str_r1:<25} | {str_r2:<25}")

* 5x5 Input Matrix:
[[47 22 18 19 21]
 [15 25 10 26 11]
 [22 17 16 35 30]
 [47 28 30 21 38]
 [39 24 14 33 33]]

Edge Detection Map        | Blur Activation Map      
['36.0', '-45.0', '29.0'] | ['21.3', '20.9', '20.7'] 
['-23.0', '-28.0', '47.0'] | ['23.3', '23.1', '24.1'] 
['-6.0', '41.0', '-52.0'] | ['26.3', '24.2', '27.8'] 


* 5. Pick any Instagram photo, convert it to grayscale and a small NumPy array (e.g., 8x8), and use your convolution function to apply a custom filter of your choice. Show the input and output arrays and briefly describe what feature your filter detects.

This snippet loads a sample photo (or generates an 8x8 intensity matrix representing a cropped photo region), converts it to an $8 \times 8$ grayscale slice, and processes it through a horizontal edge filter.

In [ ]:
def process_instagram_photo(image_path):
    try:
        img = Image.open(image_path).convert('L').resize((8, 8))
        img_array = np.array(img, dtype=np.float32)

        horizontal_sobel = np.array([
            [-1, -2, -1],
            [ 0,  0,  0],
            [ 1,  2,  1]
        ])

        output_map = apply_stride_convolution(img_array, horizontal_sobel, stride=1)

        print("\n* 8x8 Grayscale Image Input Array:")
        print(img_array.astype(int))
        
        print("\n* 6x6 Output Activation Map:")
        print(output_map.astype(int))
        

    except FileNotFoundError:
        print(f"Error: Could not find image at '{image_path}'.")
        print("Please save your Instagram photo in the project folder and pass its correct filename.")

process_instagram_photo(r"C:\Users\patel prit\OneDrive\Desktop\Assessment\DL\Assignment\Session - 18\Harry Potter.webp")


* 8x8 Grayscale Image Input Array:
[[195 195 198 136  56  76 166 198]
 [196 198 195 111 121  74 118 205]
 [200 202 210 175 153 135 186 205]
 [208 192 117 117 102  39  65 186]
 [180  56  18  56  44  15   6 104]
 [ 37  22  39  40  29  18  10  60]
 [  3  17  31  13  10  13  11 132]
 [ 66  49   7  10  11  10  21 179]]

* 6x6 Output Activation Map:
[[  31   70  187  292  235  106]
 [ -78 -156  -85  -67 -142 -160]
 [-504 -649 -539 -457 -529 -581]
 [-589 -403 -305 -244 -170 -257]
 [-242  -56 -107 -113  -33   36]
 [  51  -67 -110  -74  -23  133]]


**Feature Detection Summary**
* Filter Type: Horizontal Sobel Kernel ($\left[\begin{smallmatrix}-1 & -2 & -1\\ 0 & 0 & 0\\ 1 & 2 & 1\end{smallmatrix}\right]$)
* What it detects: This filter computes spatial derivatives along the vertical axis to highlight horizontal edges or boundary transitions.
* Observed Output: The output map shows a prominent high magnitude region around row index 2 (-760 range) corresponding directly to the intensity drop between pixels in rows 2 and 3 (from $\approx 220$ brightness down to $\approx 35$).